{{ if .Values.zookeeper.pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zookeeper-pdb
spec:
  minAvailable: {{ .Values.zookeeper.pdb.minAvailable }}
  maxUnavailable: {{ .Values.zookeeper.pdb.maxUnavailable }}
  selector:
    matchLabels:
      app: zookeeper
{{ end }}
