{{ if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  {{- range .Values.grafana.dashboardsConfigMaps }}
  name : {{ .configMapName|quote }}
  {{- end}}
  labels:
    app: {{ template "gateway.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ if .Values.grafana.customDashboard.value}}
  gateway-service-metrics.json: {{ .Values.grafana.customDashboard.value | toJson }}
  {{ else }}
  gateway-service-metrics.json: {{ .Files.Get "files/gateway-service-metrics.json" | toJson }}
  {{ end }}
{{ end }}
