apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mysql.initdbScriptsConfigMap }}
  labels:
    app: {{ template "gateway.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $val := .Values.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }} 
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-11"
    {{- if  .Values.additionalAnnotations }}
    {{- range $key, $val := .Values.additionalAnnotations }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
    {{- end }}
data:  
  create_otk_db.sql: |-
      CREATE DATABASE {{ .Values.otk.database.sql.databaseName }};
      CREATE USER '{{ .Values.otk.database.username }}'@'%' identified by '{{ .Values.otk.database.password }}';
      GRANT ALL ON {{ .Values.otk.database.sql.databaseName}}.* TO '{{ .Values.otk.database.username  }}'@'%';
      {{- if  .Values.otk.database.readOnlyConnection.enabled }}
      CREATE USER '{{ .Values.otk.database.readOnlyConnection.username }}'@'%' identified by '{{ .Values.otk.database.readOnlyConnection.password }}';
      GRANT SELECT ON {{ .Values.otk.database.sql.databaseName}}.* TO '{{ .Values.otk.database.readOnlyConnection.username  }}'@'%';
      {{- end }}
      flush privileges;
