{{ if and (.Values.otk.enabled) (not .Values.otk.database.existingSecretName)}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "otk.dbSecretName" . }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
  labels:
    app: {{ template "gateway.name" . }}
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $val := .Values.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  {{- if  .Values.additionalAnnotations }}
  annotations:
{{- range $key, $val := .Values.additionalAnnotations }}
    {{ $key }}: "{{ $val }}"
{{- end }}
{{- end }}
type: Opaque
data:
{{- if and (.Values.otk.database.useDemoDb) (eq .Values.otk.database.type "mysql")}}
  OTK_DATABASE_PASSWORD : {{.Values.database.password | b64enc }}
  OTK_DATABASE_USERNAME : {{.Values.database.username | b64enc }}
  OTK_DATABASE_DDL_PASSWORD : {{.Values.database.password | b64enc }}
  OTK_DATABASE_DDL_USERNAME : {{.Values.database.username | b64enc }}
{{- else }}
  OTK_DATABASE_PASSWORD : {{ required "Please fill in otk.database.password in values.yaml" .Values.otk.database.password | b64enc }}
  OTK_DATABASE_USERNAME : {{ required "Please fill in otk.database.username in values.yaml" .Values.otk.database.username| b64enc }}
  OTK_DATABASE_DDL_PASSWORD: {{ default .Values.otk.database.password .Values.otk.database.ddlPassword | b64enc}}
  OTK_DATABASE_DDL_USERNAME: {{ default .Values.otk.database.username .Values.otk.database.ddlUsername | b64enc}}
{{- end }}
{{ end }}