{{- if and .Values.serviceAccount.create .Values.rbac.create .Values.pmtagger.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "gateway.fullname" . }}-pm-tagger
  labels:
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ include "gateway.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ template "gateway.fullname" . }}-pm-tagger
  apiGroup: "rbac.authorization.k8s.io"
{{- end }}