{{ if not .Values.existingGatewaySecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gateway.secretName" . }}
  labels:
    app: {{ template "gateway.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $val := .Values.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  {{- if  .Values.additionalAnnotations }}
  annotations:
    "helm.sh/hook": pre-install,post-upgrade
    "helm.sh/hook-weight": "-5"
{{- range $key, $val := .Values.additionalAnnotations }}
    {{ $key }}: "{{ $val }}"
{{- end }}
{{- end }}
type: Opaque
data:
{{- if .Values.disklessConfig }}
  SSG_ADMIN_USERNAME: {{ .Values.management.username | b64enc }}
  SSG_ADMIN_PASSWORD: {{ .Values.management.password | b64enc }}
  SSG_CLUSTER_PASSWORD: {{.Values.clusterPassword | b64enc }}
  {{ if .Values.database.enabled }}
  SSG_DATABASE_USER: {{.Values.database.username | b64enc }}
  SSG_DATABASE_PASSWORD:  {{.Values.database.password | b64enc }}
  {{ end }}
{{- end }}
{{ if .Values.additionalSecret }}
{{- range $key, $val := .Values.additionalSecret }}
  {{ $key }}: {{ $val | toString | b64enc }}
{{- end }}
{{ end }}
{{ end }}