{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gateway.serviceAccountName" . }}
  annotations:
  "helm.sh/hook": pre-install
  "helm.sh/hook-weight": "-9"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "gateway.name" . }}
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
secrets:
  - name: {{ include "gateway.fullname" . }}
{{ end }}