{{ if and (.Values.tls.useSignedCertificates) (not .Values.tls.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gateway.tlsSecretName" . }}
  annotations:
    description: Default SSL Key for the SSG Gateway
  labels:
    app: {{ template "gateway.name" . }}
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  SSG_SSL_KEY: {{ .Values.tls.key | b64enc | b64enc }}
  SSG_SSL_KEY_PASS: {{ .Values.tls.pass | b64enc }}
{{ end }}
