apiVersion: v2
name: druid
description: Broadcom APIM Portal Analytics Chart
type: application
home: https://github.com/CAAPIM/apim-charts
maintainers:
  - name: Gazza7205
sources:
  - https://github.com/CAAPIM/apim-charts
version: 1.0.14
appVersion: 28.0.1
