{{ if .Values.tenantProvisioner.pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  app: tenant-provisioner
  name: tenant-provisioner-pdb
spec:
  {{- if .Values.tenantProvisioner.pdb.minAvailable }}
  minAvailable: {{ .Values.tenantProvisioner.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.tenantProvisioner.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.tenantProvisioner.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app: tenant-provisioner
{{ end }}
