apiVersion: batch/v1
kind: Job
metadata:
  name: db-upgrade
  annotations:
    chartversion: {{ .Chart.AppVersion | quote }}
  labels:
    app: {{ template "portal.name" . }}
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $val := .Values.global.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
    {{- range $key, $val := .Values.portal.jobsLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
spec:
  backoffLimit: 2
  template:
    spec:
      serviceAccountName: {{ include "portal.serviceAccountName" . }}
      containers:
        - name: db-upgrade
          image: "{{ .Values.global.portalRepository }}{{ .Values.image.dbUpgrade }}"
          env:
           - name: HOST
         {{ if .Values.global.setupDemoDatabase }}
             value: {{ .Release.Name }}-{{ .Values.global.databaseHost }}
        {{ else }}
             value: {{ .Values.global.databaseHost | quote }}
        {{ end }}
           - name: DATABASE_NAME
             value: {{ include "portal-db-name" . | quote }}
           - name: PASSWORD
             valueFrom:
               secretKeyRef:
                 name: {{ .Values.global.databaseSecret }}
            {{ if eq .Values.global.databaseType "mysql" }}
                 key: mysql-password
            {{ else if eq .Values.global.databaseType "postgres" }}
                 key: postgres-password
            {{ end }}
           - name: PORT
             value: {{ include "database-port" . | quote }}
           - name: LISTEN_PORT
             value: "8080"
           - name: USERNAME
             value: {{ required "Please fill in databaseUsername in values.yaml" .Values.global.databaseUsername | quote }}
           - name: DATABASE_TYPE
             value: {{ required "Please fill in databaseType in values.yaml" .Values.global.databaseType | quote }}
           - name: CREATE_DATABASE
             value: "true"
           - name: TSSG_TENANT_ID
             value: {{ include "default-tenant-id" . | quote }}
      {{- if .Values.global.pullSecret }}
      imagePullSecrets:
      - name: "{{ .Values.global.pullSecret }}"
      {{- end }}
      restartPolicy: "OnFailure"