apiVersion: batch/v1
kind: Job
metadata:
  name: rbac-upgrade
  annotations:
    chartversion: {{ .Chart.AppVersion | quote }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
  labels:
    app: {{ template "portal.name" . }}
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $val := .Values.global.additionalLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
    {{- range $key, $val := .Values.portal.jobsLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
spec:
  backoffLimit: 2
  template:
    spec:
      serviceAccountName: {{ include "portal.serviceAccountName" . }}
      containers:
        - name: rbac-upgrade
          image: "{{ .Values.global.portalRepository }}{{ .Values.image.rbacUpgrade }}"
          imagePullPolicy: IfNotPresent
          env:
           - name: HOST
         {{ if .Values.global.setupDemoDatabase }}
             value: {{ .Release.Name }}-{{ .Values.global.databaseHost }}
        {{ else }}
             value: {{ .Values.global.databaseHost | quote }}
        {{ end }}
           - name: DATABASE_NAME
             value: {{ include "rbac-db-name" . | quote }}
           - name: PASSWORD
             valueFrom:
               secretKeyRef:
                 name: {{ .Values.global.databaseSecret }}
            {{ if eq .Values.global.databaseType "mysql" }}
                 key: mysql-password
            {{ else if eq .Values.global.databaseType "postgres" }}
                 key: postgres-password
            {{ end }}
           - name: PORT
             value: {{ include "database-port" . | quote }}
           - name: LISTEN_PORT
             value: "8081"
           - name: USERNAME
             value: {{ required "Please fill in databaseUsername in values.yaml" .Values.global.databaseUsername | quote }}
           - name: DATABASE_TYPE
             value: {{ required "Please fill in databaseType in values.yaml" .Values.global.databaseType | quote }}
           - name: CREATE_DATABASE
             value: "true"
      {{- if .Values.global.pullSecret }}
      imagePullSecrets:
      - name: "{{ .Values.global.pullSecret }}"
      {{- end }}
      {{- if or (.Values.jobs.nodeSelector) (.Values.global.nodeSelector)}}
      nodeSelector: {{- toYaml or .Values.jobs.nodeSelector .Values.global.nodeSelector | nindent 12 }}
      {{- end }}
      {{- if or (.Values.jobs.tolerations) (.Values.global.tolerations)}}
      tolerations: {{- toYaml or .Values.jobs.tolerations .Values.global.tolerations | nindent 12 }}
      {{- end }}
      restartPolicy: "OnFailure"