apiVersion: v2
appVersion: "10.1.00"
description: This Helm Chart deploys the Layer7 Gateway in Kubernetes.
name: gateway
version: 2.0.6
type: application
home: https://github.com/CAAPIM/apim-charts
maintainers:
  - name: Gazza7205
sources:
  - https://github.com/CAAPIM/apim-charts
dependencies:
  - name: hazelcast
    version: 3.4.6
    repository: "https://hazelcast-charts.s3.amazonaws.com/"
    condition: hazelcast.enabled
  - name: influxdb
    version: 4.7.0
    repository: "https://helm.influxdata.com/"
    condition: influxdb.enabled
  - name: grafana
    version: 3.1.1
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
    condition: grafana.enabled
  - name: mysql
    version: 8.2.5
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
    condition: database.create
