apiVersion: v2
appVersion: "10.1.00_CR2"
description: This Helm Chart deploys the Layer7 Gateway in Kubernetes.
name: gateway
version: 3.0.2
type: application
home: https://github.com/CAAPIM/apim-charts
maintainers:
  - name: Gazza7205
sources:
  - https://github.com/CAAPIM/apim-charts
dependencies:
  - name: hazelcast
    version: 5.4.0
    repository: "https://hazelcast-charts.s3.amazonaws.com/"
    condition: hazelcast.enabled
  - name: influxdb
    version: 4.12.0
    repository: "https://helm.influxdata.com/"
    condition: influxdb.enabled
  - name: grafana
    version: 8.0.11
    repository: "https://charts.bitnami.com/bitnami"
    condition: grafana.enabled
  - name: mysql
    version: 9.2.6
    repository: "https://charts.bitnami.com/bitnami"
    condition: database.create
