{{ if .Values.coordinator.pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: coordinator-pdb
spec:
  {{- if .Values.coordinator.pdb.minAvailable }}
  minAvailable: {{ .Values.coordinator.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.coordinator.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.coordinator.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app: coordinator
{{ end }}
