{{ if not (.Values.portal.useExistingPullSecret) }}
{{ if or (.Values.portal.registryCredentials) (.Values.portal.imagePullSecret.enabled)  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.pullSecret }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-10"
  labels:
    app: {{ template "portal.name" . }}
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
 {{- if .Values.portal.registryCredentials }}
 {{- range $key, $value := fromYaml .Values.portal.registryCredentials }}
 {{- if eq $key "data" }}
 {{- range $value }}
  .dockerconfigjson: {{ . }}
 {{- end }}
  {{- end }}
  {{- end }}
 {{- else }}
  .dockerconfigjson: {{ template "imagePullSecret" . }}
 {{ end }}
{{ end }}
{{ end }}
