apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.tls.externalSecretName}}
  annotations:
    "helm.sh/hook": pre-install{{ if and (not .Values.tls.job.enabled) (.Values.tls.saas) }}, pre-upgrade {{ end }}
    "helm.sh/hook-weight": "-10"
  labels:
    app: {{ template "portal.name" . }}
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{ if and (not .Values.tls.job.enabled) (.Values.tls.saas) }}
  apim-ssl.crt: {{ .Values.tls.external.apimssl.crt | b64enc }}
  apim-ssl.key: {{ .Values.tls.external.apimssl.key | b64enc }}
  apim-ssl.p12: {{ .Values.tls.external.apimssl.p12 | b64enc }}
  dispatcher-ssl.crt: {{ .Values.tls.external.dispatcherssl.crt | b64enc }}
  dispatcher-ssl.key: {{ .Values.tls.external.dispatcherssl.key | b64enc }}
  dispatcher-ssl.p12: {{ .Values.tls.external.dispatcherssl.p12 | b64enc }}
  keypass.txt: {{ .Values.tls.external.keypass | b64enc | quote }}
{{ end }}
