apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.tls.internalSecretName}}
  annotations:
    "helm.sh/hook": pre-install{{ if .Values.global.saas }}, pre-upgrade {{ end }}
    "helm.sh/hook-weight": "-10"
  labels:
    app: {{ template "portal.name" . }}
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{ if and (not .Values.tls.job.enabled) (.Values.global.saas) }}
  apim-datalake.crt: {{ .Values.tls.internal.apimdatalake.crt | b64enc }}
  apim-datalake.key: {{ .Values.tls.internal.apimdatalake.key | b64enc }}
  apim-datalake.p12: {{ .Values.tls.internal.apimdatalake.p12 | b64enc }}
  apim-dssg.crt: {{ .Values.tls.internal.apimdssg.crt | b64enc }}
  apim-dssg.key: {{ .Values.tls.internal.apimdssg.key | b64enc }}
  apim-dssg.p12: {{ .Values.tls.internal.apimdssg.p12 | b64enc }}
  apim-tps.crt: {{ .Values.tls.internal.apimtps.crt | b64enc }}
  apim-tps.key: {{ .Values.tls.internal.apimtps.key | b64enc }}
  apim-tps.p12: {{ .Values.tls.internal.apimtps.p12 | b64enc }}
  pssg-ssl.crt: {{ .Values.tls.internal.pssgssl.crt | b64enc }}
  pssg-ssl.key: {{ .Values.tls.internal.pssgssl.key | b64enc }}
  pssg-ssl.p12: {{ .Values.tls.internal.pssgssl.p12 | b64enc }}
  tps.crt: {{ .Values.tls.internal.tps.crt | b64enc }}
  tps.key: {{ .Values.tls.internal.tps.key | b64enc }}
  tps.p12: {{ .Values.tls.internal.tps.p12 | b64enc }}
  keypass.txt: {{ .Values.tls.internal.keypass | b64enc | quote }}
{{ end }}
