
apiVersion: v1
kind: Secret
metadata:
  name: portal-data-secret
  labels:
    app: portal-data
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  CONFIG_MAIL_SMTP_USERNAME: {{ required "Please fill in smtp.username in values.yaml" .Values.smtp.username | b64enc | quote }}
  CONFIG_MAIL_SMTP_PASSWORD: {{ required "Please fill in smtp.password in values.yaml" .Values.smtp.password | b64enc | quote }}
  CONFIG_MAIL_SMTP_CERT: {{ include "smtp-external-crt" . | b64enc }}
  DATABASE_USERNAME: {{ required "Please fill in databaseUsername in values.yaml" .Values.global.databaseUsername | b64enc | quote }} 
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.auth.username | b64enc | quote }}
  RBAC_DATABASE_USERNAME: {{ required "Please fill in databaseUsername in values.yaml" .Values.global.databaseUsername | b64enc | quote }}  
  {{- if .Values.telemetry.proxy.url }}
  TELEMETRY_PROXY_USERNAME: {{ .Values.telemetry.proxy.username | b64enc | quote }}
  TELEMETRY_PROXY_PASSWORD: {{ .Values.telemetry.proxy.password | b64enc | quote }}
  {{- end }}
  {{ if .Values.portalData.additionalSecret }}
{{- range $key, $val := .Values.portalData.additionalSecret }}
  {{ $key }}: {{ $val | toString | b64enc }}
{{- end }}
{{ end }}