apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: secret-seaweedfs-db
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": "pre-install"
stringData:
  DATABASE_USERNAME: {{ required "Please fill in databaseUsername in values.yaml" .Values.global.databaseUsername | quote }}

