{{ if .Values.broker.pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  app: broker
  name: broker-pdb
spec:
  {{- if .Values.broker.pdb.minAvailable }}
  minAvailable: {{ .Values.broker.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.broker.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.broker.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app: broker
{{ end }}
