apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.minio.auth.secretName}} 
  labels:
    app: minio
    chart: {{ template "druid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{if .Values.minio.auth.access_key }}
  MINIO_ACCESS_KEY: {{ .Values.minio.auth.access_key | b64enc }}
{{ else }}
  MINIO_ACCESS_KEY: {{ randAlphaNum 10 | b64enc }}
{{ end }}
{{if .Values.minio.auth.secret_key }}
  MINIO_SECRET_KEY: {{ .Values.minio.auth.secret_key | b64enc }}
{{ else }}
  MINIO_SECRET_KEY: {{ randAlphaNum 40 | b64enc }}
{{ end }}
{{- if .Values.minio.gcsgateway.enabled }}
  gcs_key.json: {{ .Values.minio.gcsgateway.gcsKeyJson | b64enc }}
{{- end }}
{{- if .Values.minio.s3gateway.enabled -}}
{{- if .Values.minio.s3gateway.accessKey }}
  awsAccessKeyId: {{ .Values.minio.s3gateway.accessKey | b64enc | quote }}
{{- end }}
{{- if .Values.minio.s3gateway.secretKey }}
  awsSecretAccessKey: {{ .Values.minio.s3gateway.secretKey | b64enc | quote }}
{{- end }}
{{- end }}
