{{ if .Values.portalEnterprise.pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: portal-enterprise-pdb
spec:
  minAvailable: {{ .Values.portalEnterprise.pdb.minAvailable }}
  maxUnavailable: {{ .Values.portalEnterprise.pdb.maxUnavailable }}
  selector:
    matchLabels:
      app: portal-enterprise
{{ end }}
