apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gateway.fullname" . }}-configmap
  labels:
    app: {{ template "gateway.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ACCEPT_LICENSE: {{ .Values.license.accept | quote}}
  SSG_CLUSTER_HOST: {{ .Values.clusterHostname }}
  SSG_JVM_HEAP: {{ .Values.config.heapSize }}
{{ if .Values.database.enabled }}
  {{ if .Values.database.create }}
  SSG_DATABASE_JDBC_URL: jdbc:mysql://{{ .Release.Name }}-mysql:3306/{{ .Values.database.name }}
  {{ else }}
  SSG_DATABASE_JDBC_URL: {{ .Values.database.jdbcURL }}
  {{ end }}
{{ end }}

{{ if or (.Values.hazelcast.enabled) (.Values.hazelcast.external) }}
  EXTRA_JAVA_ARGS: {{ template "gateway.javaArgs" . }} -Dcom.l7tech.server.extension.sharedCounterProvider=externalhazelcast -Dcom.l7tech.server.extension.sharedKeyValueStoreProvider=externalhazelcast -Dcom.l7tech.server.extension.sharedClusterInfoProvider=externalhazelcast
  hazelcast-xml: |+
    <hazelcast-client
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.hazelcast.com/schema/client-config
         http://www.hazelcast.com/schema/client-config/hazelcast-client-config-5.1.xsd"
            xmlns="http://www.hazelcast.com/schema/client-config">
        <instance-name>{{ .Release.Name }}-hazelcast-{{ .Release.Namespace }}</instance-name>
        <network>
            <cluster-members>
                {{ if .Values.hazelcast.external }}
                <address>{{ required "Please set an external Hazelcast URL in values.yaml" .Values.hazelcast.url }}</address>
                {{ else }}
                 <address>{{ .Release.Name }}-hazelcast.{{ .Release.Namespace }}.svc.cluster.local:{{.Values.hazelcast.service.port}}</address>
                {{ end }}
            </cluster-members>
            <redo-operation>true</redo-operation>
        </network>
        <connection-strategy async-start="false" reconnect-mode="ON">
          <connection-retry>
            <cluster-connect-timeout-millis>-1</cluster-connect-timeout-millis>
          </connection-retry>
        </connection-strategy>
    </hazelcast-client>
{{ else }}
  EXTRA_JAVA_ARGS: {{ template "gateway.javaArgs" . }}
{{ end }}

{{ if .Values.additionalEnv }}
{{- range $key, $val := .Values.additionalEnv }}
  {{ $key }}: "{{ $val }}"
{{- end }}
{{ end }}

{{ if .Values.config.log.override }}
  log-override-properties: |-
{{ .Values.config.log.properties | indent 4 }}
{{ end }}