{{ if .Values.ingress.enabled }}
{{- $kubeTargetVersion := .Capabilities.KubeVersion.GitVersion }}
{{- if semverCompare ">=1.19-0" $kubeTargetVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
 name: {{ template "gateway.fullname" . }}-ingress
 labels:
   chart: {{ template "gateway.chart" . }}
   release: {{ .Release.Name }}
   heritage: {{ .Release.Service }}
 annotations:
{{- range $key, $val := .Values.ingress.annotations }}
   {{ $key }}: "{{ $val }}"
{{- end }}
spec:
{{- if semverCompare ">=1.19-0" $kubeTargetVersion }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
{{- end }}
  tls:
  - secretName: {{ .Values.ingress.secretName }}
    hosts:
    {{- range .Values.ingress.tlsHostnames}}
    - {{ . }}
    {{- end }}
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
{{- if semverCompare ">=1.19-0" $kubeTargetVersion }}
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ template "gateway.fullname" . }}
            port:
              number: {{ .Values.ingress.port }}
{{- else }}
      - backend:
          serviceName: {{ template "gateway.fullname" . }}
          servicePort: {{ .Values.ingress.port }}
{{- end }}
  {{if .Values.ingress.additionalHostnamesAndPorts }}
  {{- $gatewayFullName := include "gateway.fullname" . }}
  {{- range $key, $val := .Values.ingress.additionalHostnamesAndPorts }}
  - host: {{ $key }}
    http:
      paths:
{{- if semverCompare ">=1.19-0" $kubeTargetVersion }}
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ $gatewayFullName }}
            port:
              number: {{ $val }}
{{- else }}
      - backend:
          serviceName: {{ $gatewayFullName }}
          servicePort: {{ $val }}
{{- end }}
  {{- end }}
  {{ end }}
  {{ end }}
